# Generated by Django 4.1.7 on 2023-02-23 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='slug',
            field=models.SlugField(default=1, verbose_name='url'),
            preserve_default=False,
        ),
        migrations.AlterModelTable(
            name='post',
            table='posts',
        ),
    ]
