# Generated by Django 4.1.7 on 2023-02-24 18:59

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_fk_post_text_alter_post_name_alter_post_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='name',
            field=models.CharField(blank=True, db_column='some name', max_length=150, null=True, unique=True, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='post',
            name='text',
            field=models.TextField(blank=True, default=blog.models.get_default_text, verbose_name='text'),
        ),
    ]
