# Generated by Django 4.1.7 on 2023-02-24 19:10

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_post_name_alter_post_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(error_messages={'blank': 'Поле надо заполнить!', 'unique': 'Поле должно быть уникальным!'}, unique=True, verbose_name='url'),
        ),
        migrations.AlterField(
            model_name='post',
            name='text',
            field=models.TextField(blank=True, db_index=True, default=blog.models.get_default_text, verbose_name='text'),
        ),
    ]
