# Generated by Django 4.1.7 on 2023-02-24 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_post_slug_alter_post_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='id',
        ),
        migrations.AddField(
            model_name='post',
            name='myid',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='myid'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(error_messages={'blank': 'Поле надо заполнить!', 'unique': 'Поле должно быть уникальным!'}, help_text='<i>Введите URL для записи</i>', unique=True, verbose_name='url'),
        ),
    ]
