# Generated by Django 4.1.7 on 2023-02-24 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_post_pub_date_alter_post_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='choice_year',
            field=models.PositiveSmallIntegerField(choices=[(2009, 2009), (2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013)], default=2009, verbose_name='year'),
            preserve_default=False,
        ),
    ]
